import React from "react";
import { Button } from "../ui/button";
const Products = () => {
  const products = [
    {
      productname: "Rooftop Solar",
      desc: "Solar panels installed on rooftops to generate electricity for residential or commercial buildings.",
      icon: (
        <polygon
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          points="29 13 14 29 25 29 23 39 38 23 27 23"
        />
      ),
    },
    {
      productname: "Off-grid Solar",
      desc: "Standalone solar systems that operate independently of the grid, ideal for remote areas.",
      icon: (
        <polygon
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          points="29 13 14 29 25 29 23 39 38 23 27 23"
        />
      ),
    },
    {
      productname: "On-grid Solar",
      desc: "Solar systems connected to the power grid, allowing excess electricity to be sold back to the utility company.",
      icon: (
        <polygon
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          points="29 13 14 29 25 29 23 39 38 23 27 23"
        />
      ),
    },
    {
      productname: "Solar Inverter",
      desc: "Converts the direct current (DC) generated by solar panels into alternating current (AC) for use in homes or businesses",
      icon: (
        <polygon
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          points="29 13 14 29 25 29 23 39 38 23 27 23"
        />
      ),
    },
    {
      productname: "Solar Battery",
      desc: "Stores excess energy produced by solar panels for later use, ensuring power availability during outages",
      icon: (
        <polygon
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          points="29 13 14 29 25 29 23 39 38 23 27 23"
        />
      ),
    },
    {
      productname: "Solar Pump",
      desc: "A solar-powered water pumping system, often used in agriculture for irrigation and water supply.",
      icon: (
        <polygon
          strokeWidth="3"
          strokeLinecap="round"
          strokeLinejoin="round"
          fill="none"
          points="29 13 14 29 25 29 23 39 38 23 27 23"
        />
      ),
    },
  ];
  return (
    <>
      <div className="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
        <div className="max-w-xl mb-10 md:mx-auto sm:text-center lg:max-w-2xl md:mb-12">
          <h2 className="max-w-lg mb-6 font-sans text-3xl font-bold leading-none tracking-tight text-gray-900 sm:text-4xl md:mx-auto">
            <span className="relative inline-block">Our Products</span>
          </h2>
          <p className="text-base text-gray-700 md:text-lg">
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem
            accusantium doloremque rem aperiam, eaque ipsa quae.
          </p>
        </div>
        <div className="grid gap-5 mb-8 md:grid-cols-2 lg:grid-cols-3">
          {products.map((product, index) => (
            <div key={index}>
              <div className="p-5 duration-300 transform bg-white border rounded shadow-sm hover:-translate-y-2">
                <div className="flex items-center justify-center w-12 h-12 mb-4 rounded-full bg-emerald-100">
                  <svg
                    className="w-10 h-10 text-deep-purple-accent-400"
                    stroke="currentColor"
                    color="#009a8d"
                    viewBox="0 0 52 52">
                    {product.icon}
                  </svg>
                </div>
                <h6 className="mb-2 text-xl font-bold leading-5">
                  {product.productname}
                </h6>
                <p className="mb-3 text-sm text-gray-900">{product.desc}</p>
              </div>
            </div>
          ))}
        </div>
        <div className="text-center">
          <Button>Learn More</Button>
        </div>
      </div>
    </>
  );
};

export default Products;
